##############################
## HTML補完
##############################
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'plantuml']

##############################
## toml用シンタックス
##############################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

##############################
## plantuml用シンタックス
##############################
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

