##############################
## toml用シンタックス
##############################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

##############################
## plantuml用シンタックス
##############################
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'

