##############################
## dein本体
##############################
[[plugins]]
repo = 'Shougo/dein.vim'

##############################
## Unite関連plugin
##############################
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = ['unite.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite.vim']

##############################
## 非同期実行plugin
##############################
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

##############################
## git関係plugin
##############################
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'


##############################
## color scheme
##############################
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

##############################
## 他
##############################
[[plugins]]
# 全角スペースを表示
repo = 'thinca/vim-zenspace'
hook_add = '''
    augroup vimrc-highlight
      autocmd!
      autocmd ColorScheme * highlight ZenSpace ctermbg=darkgray guibg=darkgray
    augroup END
'''

[[plugins]]
# 括弧等の操作
repo = 'tpope/vim-surround'

[[plugins]]
# visualモードでの'*'を利用可能にするplugin
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
# fuzzyなfinder
repo = 'junegunn/fzf'
merged = '0'

[[plugins]]
# 同上
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    " grepのback endとしてRipGrepを使用(RipGrepは以下の様な手順で導入可能)
    "  > curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb
    "  > sudo dpkg -i ripgrep_0.10.0_amd64.deb && rm ripgrep_0.10.0_amd64.deb
    command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
    \ <bang>0 ? fzf#vim#with_preview({'options': '--exact --reverse --delimiter : --nth 4..'}, 'up:60%')
    \         : fzf#vim#with_preview({'options': '--exact --reverse --delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
    \ <bang>0)

    " ctrl+tはtmuxのprefixと重複するので、キーバインドを変更しとく
    let g:fzf_action = { 'ctrl-o': 'tab split' }
'''
